### ISSUE TITLE
Strings ending in "\\" break syntax highlighting

### ISSUE THREAD

**Issue by joshuacc** [rosshamish/kuskus#94]
The following is syntactically correct code, but it breaks syntax highlighting.

```
let myVar = "a\\";
let myOtherVar = "whatever";
```

![image](https://user-images.githubusercontent.com/171086/196248699-2432c8ce-15fb-40d8-ba7b-134e3852aa42.png)

**Comment by rosshamish** [comment]
Thanks for the report. I'll try to take a look at some point. If any other contributors want to take a stab at this, it should be some regex change in the tmlanguage file.

**Comment by rosshamish** [comment]
Looks like the Escapes section of the tmLanguage.yml needs to be updated to allow for other escape sequences. Currently it suports escaping single and double quotes. Needs \t, \n, \\. We can add a test case in `kusto-syntax-highlighting\test\snapshots\data-types\strings.kql` to cover this by putting a \\ at the end of line 22.

tmLanguage.yml, currently:
```yml
  Escapes:
    patterns:
      - match: \\['"]
        name: constant.character.escape.kusto
```

Proposed fix:
```
  Escapes:
    patterns:
      - match: \\['"tn\\]
        name: constant.character.escape.kusto
```

and then
1. `npm run convert` to convert the yml to json
2. `npm run test` to check that the tests look right
3. `npm run test:update-snapshot` to update the snapshots
